// Generated by scripts/l10n.py from localization/en.lproj/Localizable.strings.
// Do not edit by hand: edit that file and re-run `scripts/l10n.py generate`.
@file:Suppress("ObjectPropertyName", "unused")

package com.frankzhu.xiangqi.l10n

object L10n {
    object App {
        object Recovery {
            val message = LocalizedKey("app.recovery.message", "The saved game could not be validated. Its file has been preserved.")
            val title = LocalizedKey("app.recovery.title", "Saved game")
        }
    }

    object Board {
        val label = LocalizedKey("board.label", "Xiangqi board")
        val legalDestination = LocalizedKey("board.legalDestination", "Legal destination")
        val practice = LocalizedKey("board.practice", "Practice board")
        object River {
            /** River text, left half */
            val left = LocalizedKey("board.river.left", "楚 河")
            /** River text, right half */
            val right = LocalizedKey("board.river.right", "漢 界")
        }

        object Square {
            val empty = LocalizedKey("board.square.empty", "Empty %s", 1)
            /** Side, piece, square, state */
            val occupied = LocalizedKey("board.square.occupied", "%1\$s %2\$s, %3\$s, %4\$s", 4)
        }

        object State {
            val occupied = LocalizedKey("board.state.occupied", "occupied")
            val selectable = LocalizedKey("board.state.selectable", "selectable")
        }

        val study = LocalizedKey("board.study", "Study board")
    }

    object Common {
        val always = LocalizedKey("common.always", "Always")
        val cancel = LocalizedKey("common.cancel", "Cancel")
        val confirm = LocalizedKey("common.confirm", "Confirm")
        val done = LocalizedKey("common.done", "Done")
        /** Placeholder for a missing value */
        val emptyValue = LocalizedKey("common.emptyValue", "—")
        val hint = LocalizedKey("common.hint", "Hint")
        val home = LocalizedKey("common.home", "Home")
        val moves = LocalizedKey("common.moves", "Moves")
        /** Separator between two player names */
        val nameSeparator = LocalizedKey("common.nameSeparator", "–")
        val next = LocalizedKey("common.next", "Next")
        val off = LocalizedKey("common.off", "Off")
        val ok = LocalizedKey("common.ok", "OK")
        val previous = LocalizedKey("common.previous", "Previous")
        val random = LocalizedKey("common.random", "Random")
        val restart = LocalizedKey("common.restart", "Restart")
        val result = LocalizedKey("common.result", "Result")
        val resume = LocalizedKey("common.resume", "Resume")
        val settings = LocalizedKey("common.settings", "Settings")
        val source = LocalizedKey("common.source", "Source")
    }

    object Error {
        object Engine {
            val invalidMove = LocalizedKey("error.engine.invalidMove", "The computer opponent returned a move that is not valid here.")
            val networkInvalid = LocalizedKey("error.engine.networkInvalid", "The computer opponent's neural network failed its integrity check.")
            val networkMissing = LocalizedKey("error.engine.networkMissing", "The computer opponent's neural network is missing from this build.")
            val unavailable = LocalizedKey("error.engine.unavailable", "The computer opponent could not finish its move.")
        }

        val generic = LocalizedKey("error.generic", "Something went wrong.")
        object Library {
            val corruptRecord = LocalizedKey("error.library.corruptRecord", "This record could not be read.")
            val unavailable = LocalizedKey("error.library.unavailable", "The learning library could not be opened.")
            val unsupportedSchema = LocalizedKey("error.library.unsupportedSchema", "This learning library was built for a different version of the app.")
        }

        object Position {
            val invalid = LocalizedKey("error.position.invalid", "This position could not be read.")
        }

        object Progress {
            val unsupportedSchema = LocalizedKey("error.progress.unsupportedSchema", "Your saved progress was written by a newer version of the app.")
        }
    }

    object Game {
        val confirmMove = LocalizedKey("game.confirmMove", "Confirm move")
        val flip = LocalizedKey("game.flip", "Flip")
        object Hint {
            val available = LocalizedKey("game.hint.available", "Hint")
            val destination = LocalizedKey("game.hint.destination", "Hint shown")
            val searching = LocalizedKey("game.hint.searching", "Finding")
            val source = LocalizedKey("game.hint.source", "Show square")
        }

        val leave = LocalizedKey("game.leave", "Leave game")
        val menu = LocalizedKey("game.menu", "Game menu")
        object Message {
            val engineMismatch = LocalizedKey("game.message.engineMismatch", "Pikafish returned a move that does not match the current game.")
            val notSaved = LocalizedKey("game.message.notSaved", "Game not saved")
        }

        val movesAction = LocalizedKey("game.movesAction", "Moves")
        object Rail {
            val engine = LocalizedKey("game.rail.engine", "Pikafish · Level %d", 1)
            val opponent = LocalizedKey("game.rail.opponent", "OPPONENT")
            val player = LocalizedKey("game.rail.player", "PLAYER")
            val toMove = LocalizedKey("game.rail.toMove", "TO MOVE")
            val you = LocalizedKey("game.rail.you", "You · %s", 1)
        }

        object Status {
            val check = LocalizedKey("game.status.check", "Check · %s to move", 1)
            val computerToMove = LocalizedKey("game.status.computerToMove", "Computer to move")
            val draw = LocalizedKey("game.status.draw", "Draw · %s", 1)
            val reviewing = LocalizedKey("game.status.reviewing", "Reviewing move %1\$d of %2\$d", 2)
            val sideToMove = LocalizedKey("game.status.sideToMove", "%s to move", 1)
            val thinking = LocalizedKey("game.status.thinking", "Pikafish is thinking…")
            val wins = LocalizedKey("game.status.wins", "%1\$s wins · %2\$s", 2)
            val yourMove = LocalizedKey("game.status.yourMove", "Your move")
        }

        val unavailable = LocalizedKey("game.unavailable", "Game unavailable")
        val undo = LocalizedKey("game.undo", "Undo")
    }

    object GameMenu {
        val formatNote = LocalizedKey("gameMenu.formatNote", "The saved record uses the starting FEN and ordered UCI moves. Display notation is derived, so games can be replayed and exchanged without depending on the visual theme.")
        val movesValue = LocalizedKey("gameMenu.movesValue", "UCI coordinates")
        val newGame = LocalizedKey("gameMenu.newGame", "New game")
        val resign = LocalizedKey("gameMenu.resign", "Resign")
        val resignConfirm = LocalizedKey("gameMenu.resignConfirm", "Resign this game?")
        val rules = LocalizedKey("gameMenu.rules", "Rules")
        val saveAndLeave = LocalizedKey("gameMenu.saveAndLeave", "Save and leave")
        object Section {
            val format = LocalizedKey("gameMenu.section.format", "Record format")
            val game = LocalizedKey("gameMenu.section.game", "Game")
        }

        val share = LocalizedKey("gameMenu.share", "Share game record")
    }

    object History {
        val livePosition = LocalizedKey("history.livePosition", "Live position")
        /** Move pair number followed by a period */
        val moveNumber = LocalizedKey("history.moveNumber", "%d.", 1)
        val returnToLive = LocalizedKey("history.returnToLive", "Return to live")
        val title = LocalizedKey("history.title", "Moves · %d", 1)
    }

    object Home {
        object Continue {
            val hint = LocalizedKey("home.continue.hint", "Returns to the saved position")
            val subtitle = LocalizedKey("home.continue.subtitle", "%1\$s · %2\$d moves", 2)
            val title = LocalizedKey("home.continue.title", "Continue game")
        }

        object Hero {
            val subtitle = LocalizedKey("home.hero.subtitle", "Play, study, and sharpen your game—entirely offline.")
            val title = LocalizedKey("home.hero.title", "The board is ready.")
        }

        object Mode {
            object Computer {
                val subtitle = LocalizedKey("home.mode.computer.subtitle", "Challenge Pikafish offline")
            }

            object Learn {
                val subtitle = LocalizedKey("home.mode.learn.subtitle", "Puzzles and master games")
                val title = LocalizedKey("home.mode.learn.title", "Learn and practice")
            }

            object TwoPlayer {
                val subtitle = LocalizedKey("home.mode.twoPlayer.subtitle", "Share this device")
            }
        }

        object Section {
            val mode = LocalizedKey("home.section.mode", "CHOOSE A MODE")
            val theme = LocalizedKey("home.section.theme", "BOARD THEME")
        }

        /** App wordmark, Chinese */
        val title = LocalizedKey("home.title", "象棋")
        /** App wordmark, Latin */
        val wordmark = LocalizedKey("home.wordmark", "XIANGQI")
    }

    object Learn {
        object Category {
            val endgames = LocalizedKey("learn.category.endgames", "Endgames")
            val fullGameTactics = LocalizedKey("learn.category.fullGameTactics", "Full-game tactics")
            val games = LocalizedKey("learn.category.games", "Games")
            val matingPractice = LocalizedKey("learn.category.matingPractice", "Mating practice")
            val middlegames = LocalizedKey("learn.category.middlegames", "Middlegames")
            val openings = LocalizedKey("learn.category.openings", "Openings")
        }

        val couldNotLoadRecords = LocalizedKey("learn.couldNotLoadRecords", "Could not load records")
        object Dataset {
            val note = LocalizedKey("learn.dataset.note", "Dataset by Yu-Han Tseng and Bo-Nian Chen. Source records are decoded, converted to UCI, and legality-validated; ambiguous or invalid records are excluded.")
            val subtitle = LocalizedKey("learn.dataset.subtitle", "Study master games, openings, middlegames, endgames, and tactical positions entirely offline.")
            val title = LocalizedKey("learn.dataset.title", "Chinese Chess Practical Dataset")
        }

        val datasetRevision = LocalizedKey("learn.datasetRevision", "Dataset revision")
        val ecco = LocalizedKey("learn.ecco", "ECCO")
        val libraryUnavailable = LocalizedKey("learn.libraryUnavailable", "Learning library unavailable")
        val license = LocalizedKey("learn.license", "License")
        val loadingLibrary = LocalizedKey("learn.loadingLibrary", "Loading library…")
        val loadingRecords = LocalizedKey("learn.loadingRecords", "Loading records…")
        val plyCount = LocalizedKey("learn.plyCount", "%d plies", 1)
        val recordCount = LocalizedKey("learn.recordCount", "%s records", 1)
        val searchPrompt = LocalizedKey("learn.searchPrompt", "Player, tournament, opening, or year")
        object Section {
            val browse = LocalizedKey("learn.section.browse", "Browse")
        }

        object Subcategory {
            val allMatches = LocalizedKey("learn.subcategory.allMatches", "All matches")
            val ccpdComputerMatches = LocalizedKey("learn.subcategory.ccpdComputerMatches", "CCPD · Computer matches")
            val ccpdMasterMatches = LocalizedKey("learn.subcategory.ccpdMasterMatches", "CCPD · Master matches")
            val dongpingMatches = LocalizedKey("learn.subcategory.dongpingMatches", "Dongping ICCS matches")
            val title = LocalizedKey("learn.subcategory.title", "Match collection")
            val wxfMatches = LocalizedKey("learn.subcategory.wxfMatches", "WXF ICCS matches")
        }

        val title = LocalizedKey("learn.title", "Learn")
        val validatedRecords = LocalizedKey("learn.validatedRecords", "Validated records")
    }

    object Licenses {
        val apache = LocalizedKey("licenses.apache", "Apache License 2.0")
        val bundledNotice = LocalizedKey("licenses.bundledNotice", "Bundled notice")
        object Ccpd {
            val authors = LocalizedKey("licenses.ccpd.authors", "Yu-Han Tseng and Bo-Nian Chen (2026)")
            val license = LocalizedKey("licenses.ccpd.license", "Creative Commons Attribution 4.0 International")
            val licenseLink = LocalizedKey("licenses.ccpd.licenseLink", "CC BY 4.0 license")
            val name = LocalizedKey("licenses.ccpd.name", "Chinese Chess Practical Dataset (CCPD)")
            val note = LocalizedKey("licenses.ccpd.note", "Xiangqi Mobile decodes the source text, converts Chinese notation to UCI, validates move legality, and indexes accepted records for offline study. Invalid or ambiguous records are excluded.")
            val sourceLink = LocalizedKey("licenses.ccpd.sourceLink", "Dataset source")
        }

        object Engine {
            val authors = LocalizedKey("licenses.engine.authors", "Engine authors")
            val nnue = LocalizedKey("licenses.engine.nnue", "The neural-network weights have separate terms: lawful noncommercial use; commercial use requires permission.")
            val nnueTerms = LocalizedKey("licenses.engine.nnueTerms", "Pikafish NNUE terms")
            val note = LocalizedKey("licenses.engine.note", "Pikafish is distributed under GNU GPL version 3. The bundled notice and authors list are included with the application.")
            val source = LocalizedKey("licenses.engine.source", "Exact engine source revision")
        }

        val gpl = LocalizedKey("licenses.gpl", "GNU GPL v3")
        object Libraries {
            val note = LocalizedKey("licenses.libraries.note", "This Android app is built with AndroidX, Jetpack Compose, Kotlin and the kotlinx libraries, all licensed under the Apache License 2.0.")
        }

        object Section {
            val engine = LocalizedKey("licenses.section.engine", "Computer engine")
            val learning = LocalizedKey("licenses.section.learning", "Learning content")
            /** Android-only: third-party library notice */
            val libraries = LocalizedKey("licenses.section.libraries", "Android libraries")
        }

        val title = LocalizedKey("licenses.title", "Licenses")
    }

    object Mode {
        val computer = LocalizedKey("mode.computer", "Play Computer")
        val localTwoPlayer = LocalizedKey("mode.localTwoPlayer", "Two Players")
    }

    object NewGame {
        val level = LocalizedKey("newGame.level", "Level")
        object LevelDetail {
            val _1 = LocalizedKey("newGame.levelDetail.1", "A quick Pikafish search for a more forgiving game.")
            val _2 = LocalizedKey("newGame.levelDetail.2", "A responsive Pikafish opponent with credible tactics.")
            val _3 = LocalizedKey("newGame.levelDetail.3", "Consistent play for regular club players.")
            val _4 = LocalizedKey("newGame.levelDetail.4", "A focused opponent that looks further ahead.")
            val _5 = LocalizedKey("newGame.levelDetail.5", "The strongest built-in search setting.")
        }

        object LevelName {
            val _1 = LocalizedKey("newGame.levelName.1", "Beginner")
            val _2 = LocalizedKey("newGame.levelName.2", "Club learner")
            val _3 = LocalizedKey("newGame.levelName.3", "Club player")
            val _4 = LocalizedKey("newGame.levelName.4", "Expert")
            val _5 = LocalizedKey("newGame.levelName.5", "Master")
        }

        val mode = LocalizedKey("newGame.mode", "Mode")
        val redMovesFirst = LocalizedKey("newGame.redMovesFirst", "Red moves first.")
        object Replace {
            val confirm = LocalizedKey("newGame.replace.confirm", "Replace and start")
            val message = LocalizedKey("newGame.replace.message", "The current unfinished game will be replaced by this new game.")
            val title = LocalizedKey("newGame.replace.title", "Replace the saved game?")
        }

        object Section {
            val side = LocalizedKey("newGame.section.side", "Your side")
            val strength = LocalizedKey("newGame.section.strength", "Computer strength")
            val theme = LocalizedKey("newGame.section.theme", "Theme")
            val time = LocalizedKey("newGame.section.time", "Time")
        }

        val start = LocalizedKey("newGame.start", "Start game")
        val title = LocalizedKey("newGame.title", "New game")
    }

    object Piece {
        val advisor = LocalizedKey("piece.advisor", "Advisor")
        val cannon = LocalizedKey("piece.cannon", "Cannon")
        val chariot = LocalizedKey("piece.chariot", "Chariot")
        val elephant = LocalizedKey("piece.elephant", "Elephant")
        val general = LocalizedKey("piece.general", "General")
        val horse = LocalizedKey("piece.horse", "Horse")
        val soldier = LocalizedKey("piece.soldier", "Soldier")
    }

    object Practice {
        val chooseDestination = LocalizedKey("practice.chooseDestination", "Choose a destination.")
        val completed = LocalizedKey("practice.completed", "Line complete. Well done.")
        val correct = LocalizedKey("practice.correct", "Correct. The recorded reply has been played.")
        val couldNotOpen = LocalizedKey("practice.couldNotOpen", "Could not open practice")
        val findRecordedMove = LocalizedKey("practice.findRecordedMove", "Find the next move in the recorded line.")
        val hintFormat = LocalizedKey("practice.hintFormat", "Hint: %s", 1)
        val incorrect = LocalizedKey("practice.incorrect", "Not the recorded move. Try again.")
        val mistakes = LocalizedKey("practice.mistakes", "Mistakes: %d", 1)
        val moveProgress = LocalizedKey("practice.moveProgress", "Move %1\$d of %2\$d", 2)
        val opening = LocalizedKey("practice.opening", "Opening practice…")
        val studyLine = LocalizedKey("practice.studyLine", "Study line")
        val title = LocalizedKey("practice.title", "Practice")
    }

    object Privacy {
        val contact = LocalizedKey("privacy.contact", "For privacy questions, contact Frank Zhu through the linked GitHub issue tracker. Google may process Play Store, device-backup, and crash information under its own privacy settings and policies.")
        val retention = LocalizedKey("privacy.retention", "Local data remains until it is replaced or you uninstall the app or clear its storage in Android Settings. Backups and copies you have shared must be managed separately with their respective services. The developer holds no server copy of your games or settings.")
        object Section {
            val contact = LocalizedKey("privacy.section.contact", "Contact")
            val retention = LocalizedKey("privacy.section.retention", "Retention and deletion")
            val sharing = LocalizedKey("privacy.section.sharing", "Sharing and external links")
            val storage = LocalizedKey("privacy.section.storage", "Data on your device")
        }

        val sharing = LocalizedKey("privacy.sharing", "When you choose Share, the game record is passed to the recipient or service you select. Opening source-code or support links takes you to GitHub, which applies its own privacy policy. Information you submit in a GitHub issue may be public; avoid including private information.")
        val storage = LocalizedKey("privacy.storage", "Saved games, learning progress, and settings stay in the app’s storage on your device. The bundled computer engine processes positions locally. Android cloud backup and device-to-device transfer of app data are turned off, so the system does not copy this data off your device.")
        val summary = LocalizedKey("privacy.summary", "Xiangqi is developed by Frank Zhu. The app works offline and does not collect or transmit personal data to the developer. It has no accounts, advertising, tracking, analytics, or automatic diagnostic uploads.")
        val title = LocalizedKey("privacy.title", "Privacy policy")
        val updated = LocalizedKey("privacy.updated", "Updated 4 October 2026")
    }

    object Reason {
        val checkmate = LocalizedKey("reason.checkmate", "Checkmate")
        val repetition = LocalizedKey("reason.repetition", "Repetition")
        val resignation = LocalizedKey("reason.resignation", "Resignation")
        val rulesAdjudication = LocalizedKey("reason.rulesAdjudication", "Rules adjudication")
        val stalemate = LocalizedKey("reason.stalemate", "Stalemate")
        val timeLoss = LocalizedKey("reason.timeLoss", "Time loss")
    }

    object Result {
        val complete = LocalizedKey("result.complete", "Game complete")
        val draw = LocalizedKey("result.draw", "Draw")
        val review = LocalizedKey("result.review", "Review moves")
        object Summary {
            val hints = LocalizedKey("result.summary.hints", "Hints")
            val moves = LocalizedKey("result.summary.moves", "Moves")
            val time = LocalizedKey("result.summary.time", "Time")
        }

        val wins = LocalizedKey("result.wins", "%s wins", 1)
    }

    object Rules {
        val advisor = LocalizedKey("rules.advisor", "Moves one point diagonally inside the palace.")
        val cannon = LocalizedKey("rules.cannon", "Moves like a chariot, but captures by jumping exactly one intervening piece.")
        val chariot = LocalizedKey("rules.chariot", "Moves any distance along a clear file or rank.")
        val elephant = LocalizedKey("rules.elephant", "Moves two points diagonally, cannot jump, and cannot cross the river.")
        val general = LocalizedKey("rules.general", "Moves one point orthogonally inside the palace. The generals may not face on an open file.")
        val goal = LocalizedKey("rules.goal", "Checkmate the opposing general. Red moves first. A side with no legal move loses.")
        val horse = LocalizedKey("rules.horse", "Moves one orthogonal step then one diagonal step; the first step cannot be blocked.")
        val notation = LocalizedKey("rules.notation", "Files are a–i and ranks are 0–9. A move such as b2e2 records its source and destination. The game stores the starting FEN plus this ordered move list for reliable replay and sharing.")
        object Section {
            val goal = LocalizedKey("rules.section.goal", "Goal")
            val notation = LocalizedKey("rules.section.notation", "Notation")
            val pieces = LocalizedKey("rules.section.pieces", "Pieces")
        }

        val soldier = LocalizedKey("rules.soldier", "Moves forward one point. After crossing the river it may also move sideways, never backward.")
        val title = LocalizedKey("rules.title", "Rules")
    }

    object Settings {
        val appLanguage = LocalizedKey("settings.appLanguage", "App language")
        val computer = LocalizedKey("settings.computer", "Computer")
        val confirmMoves = LocalizedKey("settings.confirmMoves", "Confirm moves")
        val coordinates = LocalizedKey("settings.coordinates", "Coordinates")
        object CoordinatesOption {
            val redPerspective = LocalizedKey("settings.coordinatesOption.redPerspective", "Red perspective")
        }

        val engineNote = LocalizedKey("settings.engineNote", "Computer play uses the bundled Pikafish engine and NNUE network entirely on-device. No account or network access is required.")
        val haptics = LocalizedKey("settings.haptics", "Haptics")
        val howToPlay = LocalizedKey("settings.howToPlay", "How to play")
        object Language {
            val english = LocalizedKey("settings.language.english", "English")
            val simplifiedChinese = LocalizedKey("settings.language.simplifiedChinese", "Simplified Chinese")
            val system = LocalizedKey("settings.language.system", "System Default")
            val traditionalChinese = LocalizedKey("settings.language.traditionalChinese", "Traditional Chinese")
        }

        val licenses = LocalizedKey("settings.licenses", "Open-source and content licenses")
        val moveRecord = LocalizedKey("settings.moveRecord", "Move record")
        val pieceLabels = LocalizedKey("settings.pieceLabels", "Piece labels")
        object PieceLabelsOption {
            val simplified = LocalizedKey("settings.pieceLabelsOption.simplified", "Simplified Chinese")
            val traditional = LocalizedKey("settings.pieceLabelsOption.traditional", "Traditional Chinese")
        }

        val reportIssue = LocalizedKey("settings.reportIssue", "Report an issue on GitHub")
        val rulesPolicy = LocalizedKey("settings.rulesPolicy", "Rules policy")
        val rulesPolicyExplanation = LocalizedKey("settings.rulesPolicyExplanation", "New games use Pikafish’s rules for repetition, perpetual checking and chasing, the 60-move rule, and insufficient material. Perpetual checking or chasing can result in a loss rather than a draw. Earlier saved games keep their recorded rules.")
        val rulesPolicyName = LocalizedKey("settings.rulesPolicyName", "Pikafish Computer Rule")
        object Section {
            val about = LocalizedKey("settings.section.about", "About")
            val appearance = LocalizedKey("settings.section.appearance", "Appearance")
            val interaction = LocalizedKey("settings.section.interaction", "Interaction")
            val language = LocalizedKey("settings.section.language", "Language")
            val rules = LocalizedKey("settings.section.rules", "Rules and records")
        }

        val sounds = LocalizedKey("settings.sounds", "Sound effects")
        val soundsPreviewHint = LocalizedKey("settings.soundsPreviewHint", "Turning this on plays a sample.")
        val sourceCode = LocalizedKey("settings.sourceCode", "Source code on GitHub")
        val theme = LocalizedKey("settings.theme", "Theme")
        val title = LocalizedKey("settings.title", "Settings")
        val version = LocalizedKey("settings.version", "Version")
    }

    object Side {
        val black = LocalizedKey("side.black", "Black")
        val red = LocalizedKey("side.red", "Red")
    }

    object Study {
        val attribution = LocalizedKey("study.attribution", "CCPD · CC BY 4.0 · Modified by decoding, notation normalization, and legality validation.")
        val bookmark = LocalizedKey("study.bookmark", "Bookmark")
        val couldNotOpen = LocalizedKey("study.couldNotOpen", "Could not open record")
        val moveNumber = LocalizedKey("study.moveNumber", "%d.", 1)
        val opening = LocalizedKey("study.opening", "Opening record…")
        val plyProgress = LocalizedKey("study.plyProgress", "%1\$d / %2\$d", 2)
        val practice = LocalizedKey("study.practice", "Practice")
        val recordMissing = LocalizedKey("study.recordMissing", "The record is not present in this library.")
        val removeBookmark = LocalizedKey("study.removeBookmark", "Remove bookmark")
        val title = LocalizedKey("study.title", "Study")
    }

    object Theme {
        /** Accessibility label for a theme swatch */
        val accessibilityLabel = LocalizedKey("theme.accessibilityLabel", "%s theme", 1)
        val calm = LocalizedKey("theme.calm", "Calm")
        val classic = LocalizedKey("theme.classic", "Classic")
        val tournament = LocalizedKey("theme.tournament", "Tournament")
    }

    object TimeControl {
        val casual = LocalizedKey("timeControl.casual", "Casual")
        val fifteenMinutes = LocalizedKey("timeControl.fifteenMinutes", "15 min")
        val tenMinutes = LocalizedKey("timeControl.tenMinutes", "10 min")
    }
}
