#!/usr/bin/env python3
"""Keep the typed Kotlin string keys and the runtime catalogs in sync with the
localization files.

localization/en.lproj/Localizable.strings is the source of truth for the key
set, its English fallback text and translator comments; zh-Hans.lproj and
zh-Hant.lproj translate the same keys. The files use the same format as the
iOS app (https://github.com/frankmanzhu/xiangqi-mobile), so translations can be
copied between the two projects unchanged.

    scripts/l10n.py generate   # rewrite Strings.kt and the assets/l10n catalogs
    scripts/l10n.py check      # exit 1 on drift, missing translations, unused keys
"""

import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LOCALIZATIONS = os.path.join(ROOT, "localization")
APP_MAIN = os.path.join(ROOT, "app", "src", "main")
GENERATED = os.path.join(APP_MAIN, "java", "com", "frankzhu", "xiangqi", "l10n", "Strings.kt")
CATALOGS = os.path.join(APP_MAIN, "assets", "l10n")
SOURCE_LANGUAGE = "en"
REQUIRED_LANGUAGES = ("en", "zh-Hans", "zh-Hant")

KOTLIN_KEYWORDS = {
    "as", "break", "class", "continue", "do", "else", "false", "for", "fun", "if", "in",
    "interface", "is", "null", "object", "package", "return", "super", "this", "throw",
    "true", "try", "typealias", "typeof", "val", "var", "when", "while",
}

PLACEHOLDER = re.compile(r"%(?:(\d+)\$)?(lld|[@a-zA-Z])")

ENTRY = re.compile(
    r"""(?:/\*\s*(?P<comment>.*?)\s*\*/\s*)?
        "(?P<key>(?:[^"\\]|\\.)*)"\s*=\s*"(?P<value>(?:[^"\\]|\\.)*)"\s*;""",
    re.DOTALL | re.VERBOSE,
)


def unescape(value):
    return value.replace('\\"', '"').replace("\\n", "\n").replace("\\\\", "\\")


def strings_path(language):
    return os.path.join(LOCALIZATIONS, f"{language}.lproj", "Localizable.strings")


def load_strings(language):
    with open(strings_path(language), encoding="utf-8") as handle:
        text = handle.read()
    entries = {}
    for match in ENTRY.finditer(text):
        entries[unescape(match.group("key"))] = (unescape(match.group("value")), match.group("comment"))
    return entries


def placeholder_count(value):
    tokens = PLACEHOLDER.findall(value)
    if not tokens:
        return 0
    positional = [int(index) for index, _ in tokens if index]
    return max(positional) if positional else len(tokens)


def to_format(value):
    """Convert Apple format specifiers to java.util.Formatter ones."""
    def convert(match):
        index, kind = match.group(1), match.group(2)
        spec = "d" if kind in ("lld", "d") else "s"
        return f"%{index}${spec}" if index else f"%{spec}"
    return PLACEHOLDER.sub(convert, value)


def identifier(segment):
    parts = [p for p in re.split(r"[^0-9A-Za-z]+", segment) if p]
    head = parts[0]
    name = head[0].lower() + head[1:] + "".join(p[0].upper() + p[1:] for p in parts[1:])
    if name[0].isdigit():
        name = "_" + name
    return "`" + name + "`" if name in KOTLIN_KEYWORDS else name


def type_name(segment):
    return "".join(p[0].upper() + p[1:] for p in re.split(r"[^0-9A-Za-z]+", segment) if p)


def build_tree(source):
    tree = {}
    for key in sorted(source):
        node = tree
        segments = key.split(".")
        for segment in segments[:-1]:
            node = node.setdefault(segment, {})
            if not isinstance(node, dict):
                raise SystemExit(f"key '{key}' collides with a parent key")
        if segments[-1] in node:
            raise SystemExit(f"key '{key}' collides with a nested namespace")
        english, comment = source[key]
        node[segments[-1]] = (key, english, comment)
    return tree


def kotlin_escape(value):
    return (value.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$").replace("\n", "\\n"))


def render(node, indent, lines):
    pad = "    " * indent
    for name in sorted(node):
        child = node[name]
        if isinstance(child, dict):
            lines.append(f"{pad}object {type_name(name)} {{")
            render(child, indent + 1, lines)
            lines.append(f"{pad}}}")
            lines.append("")
        else:
            key, english, comment = child
            count = placeholder_count(english)
            if comment:
                lines.append(f"{pad}/** {comment.replace('*/', '* /')} */")
            lines.append(
                f'{pad}val {identifier(name)} = LocalizedKey("{kotlin_escape(key)}", '
                f'"{kotlin_escape(to_format(english))}"' + (f", {count}" if count else "") + ")"
            )
    while lines and lines[-1] == "":
        lines.pop()


def generate_source(source):
    lines = [
        "// Generated by scripts/l10n.py from localization/en.lproj/Localizable.strings.",
        "// Do not edit by hand: edit that file and re-run `scripts/l10n.py generate`.",
        "@file:Suppress(\"ObjectPropertyName\", \"unused\")",
        "",
        "package com.frankzhu.xiangqi.l10n",
        "",
        "object L10n {",
    ]
    body = []
    render(build_tree(source), 1, body)
    lines.extend(body)
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def generate_catalog(language):
    entries = load_strings(language)
    return json.dumps(
        {key: to_format(value) for key, (value, _) in sorted(entries.items())},
        ensure_ascii=False, indent=1, sort_keys=True,
    ) + "\n"


def missing_translations(source):
    problems = []
    for language in REQUIRED_LANGUAGES:
        if language == SOURCE_LANGUAGE:
            continue
        translations = load_strings(language)
        for key in sorted(source):
            if not translations.get(key, ("", None))[0]:
                problems.append(f"{key}: missing {language}")
            elif placeholder_count(translations[key][0]) != placeholder_count(source[key][0]):
                problems.append(f"{key}: placeholder count differs in {language}")
        for key in sorted(set(translations) - set(source)):
            problems.append(f"{key}: {language} has no {SOURCE_LANGUAGE} source")
    return problems


def unused_keys(source):
    used = set()
    for directory, _, files in os.walk(os.path.join(APP_MAIN, "java")):
        for name in files:
            if not name.endswith(".kt") or name == "Strings.kt":
                continue
            with open(os.path.join(directory, name), encoding="utf-8") as handle:
                used.update(m.group(0) for m in re.finditer(r"L10n(?:\.[A-Za-z0-9_`]+)+", handle.read()))
    unused = []
    for key in source:
        segments = key.split(".")
        path = "L10n" + "".join("." + type_name(s) for s in segments[:-1]) + "." + identifier(segments[-1]).strip("`")
        if path not in used:
            unused.append(key)
    return sorted(unused)


def read(path):
    try:
        with open(path, encoding="utf-8") as handle:
            return handle.read()
    except FileNotFoundError:
        return ""


def write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(text)


def main():
    command = sys.argv[1] if len(sys.argv) > 1 else "generate"
    source = load_strings(SOURCE_LANGUAGE)
    outputs = {GENERATED: generate_source(source)}
    for language in REQUIRED_LANGUAGES:
        outputs[os.path.join(CATALOGS, f"{language}.json")] = generate_catalog(language)

    if command == "generate":
        for path, text in outputs.items():
            write(path, text)
        print(f"Generated {len(source)} keys -> {os.path.relpath(GENERATED, ROOT)} + {len(REQUIRED_LANGUAGES)} catalogs")
        problems = missing_translations(source)
        if problems:
            print(f"warning: {len(problems)} translation problems")
        return 0

    if command == "check":
        failures = [f"{os.path.relpath(p, ROOT)} is stale; run `scripts/l10n.py generate`"
                    for p, text in outputs.items() if read(p) != text]
        failures += missing_translations(source)
        failures += [f"{key}: not referenced by any screen" for key in unused_keys(source)]
        if failures:
            for failure in failures:
                print(f"error: {failure}", file=sys.stderr)
            return 1
        print(f"{len(source)} keys: translated, referenced, and in sync.")
        return 0

    print(__doc__, file=sys.stderr)
    return 2


if __name__ == "__main__":
    sys.exit(main())
